const allowedLocation = [
    'tất cả địa điểm',
    'hà nội',
    'hồ chí minh',
    'an giang',
    'bà rịa - vũng tàu',
    'bắc giang',
    'bắc kạn',
    'bạc liêu',
    'bắc ninh',
    'bến tre',
    'bình định',
    'bình dương',
    'bình phước',
    'bình thuận',
    'cà mau',
    'cần thơ',
    'cao bằng',
    'cửu long',
    'đà nẵng',
    'đắc nông',
    'đắk lắk',
    'điện biên',
    'đồng nai',
    'đồng tháp',
    'gia lai',
    'hà giang',
    'hà nam',
    'hà tĩnh',
    'hải dương',
    'hải phòng',
    'hậu giang',
    'hoà bình',
    'hưng yên',
    'khánh hoà',
    'kiên giang',
    'kon tum',
    'lai châu',
    'lâm đồng',
    'lạng sơn',
    'lào cai',
    'long an',
    'miền bắc',
    'miền nam',
    'miền trung',
    'nam định',
    'nghệ an',
    'ninh bình',
    'ninh thuận',
    'phú thọ',
    'phú yên',
    'quảng bình',
    'quảng nam',
    'quảng ngãi',
    'quảng ninh',
    'quảng trị',
    'sóc trăng',
    'sơn la',
    'tây ninh',
    'thái bình',
    'thái nguyên',
    'thanh hoá',
    'thừa thiên huế',
    'tiền giang',
    'toàn quốc',
    'trà vinh',
    'tuyên quang',
    'vĩnh long',
    'vĩnh phúc',
    'yên bái',
    'nước ngoài',
    'khác'
]

const allowdCategories = [
    'tất cả ngành nghề',
    'an toàn lao động',
    'khoa học - kỹ thuật',
    'bán buôn',
    'thông tin - truyền thông',
    'bảo hiểm',
    'bảo trì - sửa chữa',
    'bất động sản',
    'biên - phiên dịch',
    'bưu chính - viễn thông',
    'cơ khí - chế tạo - tự động hóa',
    'công nghệ cao',
    'công nghệ ô tô',
    'công nghệ thông tin',
    'dệt may - da giày',
    'khai thác năng lượng - khoáng sản',
    'dịch vụ khách hàng',
    'điện - điện tử - điện lạnh',
    'điện tử viễn thông',
    'dược phẩm - công nghệ sinh học',
    'giáo dục - đào tạo',
    'hàng tiêu dùng',
    'hành chính - văn phòng',
    'hoá học - sinh học',
    'hoạch định - dự án',
    'in ấn - xuất bản',
    'it phần cứng - mạng',
    'it phần mềm',
    'kế toán - kiểm toán',
    'khách sạn - nhà hàng - du lịch',
    'kiến trúc - thiết kế nội thất',
    'kinh doanh',
    'logistics',
    'luật - pháp lý',
    'marketing',
    'môi trường - xử lý chất thải',
    'mỹ phẩm - trang sức',
    'thiết kế - sáng tạo nghệ thuật',
    'ngân hàng',
    'ngành nghề khác',
    'ngo - phi chính phủ - phi lợi nhuận',
    'nhân sự',
    'nông - lâm - ngư nghiệp',
    'quản lý chất lượng (qa-qc)',
    'quản lý điều hành',
    'tài chính - đầu tư',
    'thiết kế đồ họa',
    'thời trang',
    'thư ký - trợ lý',
    'thực phẩm - đồ uống',
    'tổ chức sự kiện - quà tặng',
    'tư vấn',
    'vận tải - kho vận',
    'xây dựng',
    'xuất nhập khẩu',
    'y tế'
]

export {
    allowedLocation,
    allowdCategories
}